### ISSUE TITLE
Make pipwin executable as a module

### ISSUE THREAD

**Issue by orlp** [lepisma/pipwin#20]
You can run pip by invoking the module directly:

    python3 -m pip ...

This has the advantage that it doesn't require any executables in path other than Python, and always finds the right `pip` for the right python version. It would be nice if we could do the same for pipwin.

**Comment by lepisma** [comment]
Ah right, a question first. _Does_ pipwin work for you? Builds are failing and I am not on Windows these days so don't know whats happening.

**Comment by orlp** [comment]
Yes, it seems to work for me.

**Comment by lepisma** [comment]
Cool. I will try doing it this weekend.

**Comment by lepisma** [comment]
Sorry for the delay. Didn't realize it was just a couple of lines. Check after 68c0a79fabf5ab4fce0d590a3db4a7a8b9cdf41a.
