### ISSUE TITLE
download destination option

### ISSUE THREAD

**Issue by daewonyoon** [lepisma/pipwin#25]
download destination option.
just like `pip`
  `pip donwload -d <dest_folder> packaage`

**Comment by lepisma** [comment]
Try now

**Comment by daewonyoon** [comment]
> C:\Temp>py -3 -m pipwin download scipy -d a
> Package `scipy` found in cache
> Downloading package . . .
> https://download.lfd.uci.edu/pythonlibs/n1rrk3iq/scipy-1.0.0-cp36-cp36m-win_amd64.whl
> scipy-1.0.0-cp36-cp36m-win_amd64.whl
> 0% [##############################] 100% | ETA: 23:59:59
> Total time elapsed: 00:00:21
> 
> C:\Temp>py -3 -m pipwin download -d a numpy
> usage: pipwin [-h] [-r [FILE]] [-d [DEST]]
>               {install,uninstall,download,search,list,refresh} [package]
> pipwin: error: unrecognized arguments: numpy
> 
> C:\Temp>py -3 -m pipwin download --dest a numpy
> usage: pipwin [-h] [-r [FILE]] [-d [DEST]]
>               {install,uninstall,download,search,list,refresh} [package]
> pipwin: error: unrecognized arguments: numpy
> 
> C:\Temp>py -3 -m pipwin --dest a download numpy
> Package `numpy` found in cache
> Downloading package . . .
> https://download.lfd.uci.edu/pythonlibs/n1rrk3iq/numpy-1.14.0+mkl-cp36-cp36m-win_amd64.whl
> numpy-1.14.0+mkl-cp36-cp36m-win_amd64.whl
> 0% [#######                       ] 100% | ETA: 00:02:09

**Comment by lepisma** [comment]
Right, argparse is pretty stupid. I will switch to [docopt](https://github.com/docopt/docopt/) this weekend. That should fix it.

**Comment by lepisma** [comment]
Migrated to docopt. Try now.

**Comment by daewonyoon** [comment]
great. works good. 

thanks.

**Comment by daewonyoon** [comment]
oops `-r option` doesn't work for `download` command after the change.

```
D:\temp>py -3 -m pipwin download -r requirements_mpack.txt
Usage:
  pipwin install <package> [-r=<file> | --file=<file>]
  pipwin uninstall <package>
  pipwin download <package> [-d=<dest> | --dest=<dest>]
  pipwin search <package>
  pipwin list
  pipwin refresh
  pipwin (-h | --help)
  pipwin (-v | --version)
```

**Comment by lepisma** [comment]
Sorry, missed that case. Should be okay now (`v0.4.2`).

**Comment by daewonyoon** [comment]
works beautiful. 

i really appreciate your effort. i just needed this tool.
