### ISSUE TITLE
if action to an entry of requirements.txt fails, the whole action is aborted.

### ISSUE THREAD

**Issue by daewonyoon** [lepisma/pipwin#27]
for example, i tried `pipwin download -r requirements.txt`.

if one entry fails, the download for the entries below seems to be simply aborted.

not sure if it is a `bug`. however, the behavior of `pip` is just to try other entries even if one entry fails.

(for my error case, the failure was because pipwin couldn't find the package by the name i specified.)

**Comment by lepisma** [comment]
Try now. The message might be ugly (it repeats `try pipwin refresh` for each missing package) but works now.

**Comment by daewonyoon** [comment]
yeah. works.

thanks.
