### ISSUE TITLE
module 'pipwin' has no attribute 'PipwinCache'

### ISSUE THREAD

**Issue by petobens** [lepisma/pipwin#3]
Hi, tried using `pipwin` but I get the following errors:

![screenshot-02-11-2015_14-33-46](https://cloud.githubusercontent.com/assets/2583971/10889164/0e8308c0-816f-11e5-8bb9-db7c9ee4c3c4.png)

Am I doing something wrong? For the record I'm using Python 3.5. Thanks!!!

**Comment by lepisma** [comment]
Looks like python version issue. Will fix it soon. Thanks for notifying.

**Comment by petobens** [comment]
Thank you! One extra question: can `pipwin` read a requirement file? If it cannot, is it a feature you might add?

**Comment by lepisma** [comment]
It can't right now. Mostly because of occasional differences in package names in PyPI's vs Gohlke's list. I will add this feature (its actually useful) too once I get time.

**Comment by petobens** [comment]
Yeah, I also find it really useful. Once again thanks.

**Comment by lepisma** [comment]
Try now, should be fixed.
I am filing `requirement` file as another issue.

**Comment by petobens** [comment]
Thank you!  I'll give a try as soon as I get some time.
