### ISSUE TITLE
[Issue] Bad import in robobrowser/browser.py

### ISSUE THREAD

**Issue by Rawleenc** [lepisma/pipwin#36]
Hi there,
As of today, when I try to use pipwin there's an exception :
```
ImportError: cannot import name 'cached_property' from 'werkzeug' (D:\MYFOLDER\COURS\3eme_annee_ESIPE\Last Project\python-venv\lpp\lib\site-packages\werkzeug\__init__.py)
```
This exception is solved by changing this import : 
```
from werkzeug import cached_property
```
By this import :
```
from werkzeug.utils import cached_property
```
In robobrowser/browser.py file line 8
Hope you'll fix this soon.

**Comment by Barazok** [comment]
Here is my pull request on the robobrowser repository :
https://github.com/jmcarp/robobrowser/pull/94

**Comment by Barazok** [comment]
robobrowser jmcarp repository seems to not be maintained anymore. I suggest you to choose one of it's numberous fork...
