### ISSUE TITLE
[Issue] Bad import in robobrowser/browser.py

### ISSUE THREAD

**Issue by Rawleenc** [lepisma/pipwin#37]
Hi there,
As of today, when I try to use pipwin there's an exception :
```
ImportError: cannot import name 'cached_property' from 'werkzeug' (D:\MYFOLDER\COURS\3eme_annee_ESIPE\Last Project\python-venv\lpp\lib\site-packages\werkzeug\__init__.py)
```
This exception is solved by changing this import : 
```
from werkzeug import cached_property
```
By this import :
```
from werkzeug.utils import cached_property
```
In robobrowser/browser.py file line 8
Hope you'll fix this soon.

Here is my pull request on the robobrowser repository :
https://github.com/jmcarp/robobrowser/pull/94

however robobrowser jmcarp repository seems to not be maintained anymore...

**Comment by NicolasCaous** [comment]
Pipwin latest build is broken with this error :( please release a fix @lepisma

**Comment by lepisma** [comment]
Not very sure what can we do here. I can pin "Werkzeug==0.16.1" in pipwin here. That should work? I have a branch for this [here](https://github.com/lepisma/pipwin/tree/pin-werkzeug). Can you confirm if this works for now?

**Comment by NicolasCaous** [comment]
Since this is a bug in robobrowser, you could pin the latest working release of robobrowser until they fix it on their repository. That should make pipwin work again.

**Comment by Rawleenc** [comment]
@lepisma I've just tested your branch and when I run `python pipwin.py` I get the following traceback : 
```
(pipwin) C:\Users\pilotage\PycharmProjects\pipwin\pipwin>python pipwin.py
Building cache. Hang on . . .
Traceback (most recent call last):
  File "pipwin.py", line 335, in <module>
    refresh()
  File "pipwin.py", line 331, in refresh
    PipwinCache(refresh=True)
  File "pipwin.py", line 210, in __init__
    self.data = build_cache()
  File "pipwin.py", line 100, in build_cache
    dl_function = re.search(r'function dl.*\}', soup.find("script").text).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```
After a quick review I saw that in the page returned by `soup.open(MAIN_URL)` the script tag does not contain the pattern `function dl.*\}` that you are searching for.

**Comment by samapriya** [comment]
@lepisma Made pull request for v0.4.7 to resolve both issues

**Comment by Rawleenc** [comment]
@samapriya please check out https://github.com/lepisma/pipwin/pull/38#issuecomment-587348704

**Comment by Rawleenc** [comment]
@lepisma 
@samapriya's pull request is now fixing this issue.
Please check out https://github.com/lepisma/pipwin/pull/38

**Comment by Rawleenc** [comment]
@lepisma, can you please merge @samapriya's pull request ?

**Comment by lepisma** [comment]
hi, i did a few review comments on the PR. waiting for those to be resolved. i can go ahead and fix those but wanted to have @samapriya's thought.

**Comment by samapriya** [comment]
Hi @lepisma 
I don't see any additional comments on the PR, could you point me to it? Here is what is visible to me

![pipwin_pr](https://user-images.githubusercontent.com/6677629/75782235-99e3aa80-5d2c-11ea-8d61-7ed17a78b031.gif)

**Comment by lepisma** [comment]
sorry, i didn't do the final press of `submit` button :|

try now

**Comment by samapriya** [comment]
Thanks @lepisma 
All changes have now been made :)

**Comment by lepisma** [comment]
merged

**Comment by samapriya** [comment]
Awesome thanks @lepisma 
feel free to close this issue :)

**Comment by Rawleenc** [comment]
Thanks for that.
I'm glad it's working again :)
I'm closing this issue as resolved.
