### ISSUE TITLE
corrupt wheels — 404 errors

### ISSUE THREAD

**Issue by rcoup** [lepisma/pipwin#40]
eg. `pipwin download gdal==3.0.4` results in a file `GDAL-3.0.4-cp37-cp37m-win_amd64.whl` with the html contents of a 404 page. Happens with other packages as well.

Maybe `PipwinCache._download()` could do with adding a [`res.raise_for_status()` call](https://requests.readthedocs.io/en/master/user/quickstart/#response-status-codes) after :294, so any HTTP errors are propagated correctly.
https://github.com/lepisma/pipwin/blob/75a0bd734f9cfb94c020f17cdcac019860bb1137/pipwin/pipwin.py#L294

**Comment by lepisma** [comment]
right, I might not be super fast in fixing this. open for PR though.

**Comment by tobinjones** [comment]
FYI I believe the root cause these 404 errors is that the server is rejecting the User-Agent you use (`PostmanRuntime/7.22.0`). If I set it to something like:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36` then things work.

**Comment by lepisma** [comment]
can you try 0.4.8 now. haven't uploaded to pypi yet since twine is giving me error. check master.

**Comment by lepisma** [comment]
pushed to pypi

**Comment by rcoup** [comment]
LGTM, thanks ⭐️
