### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by bblue** [lepisma/pipwin#43]
The following line raises an AttributeError when the cache is being rebuilt. Seems `re.search ` can return `None`. Not sure what the underlying issue is, but the error should at least exit the method a bit more graceful.

https://github.com/lepisma/pipwin/blob/73e0d9817cf0281e1b012bcf7b12808f9761d895/pipwin/pipwin.py#L103

**Comment by bblue** [comment]
Did a bit more digging. RoboBrowser response is 404, and hence the `re.search `or `soup.find` has nothing to dig through. I never did much with web crawling, so someone a bit more skilled with that should figure out what is wrong with the connection to gohlke's site. I bet this affects pretty much every user of pipwin.

**Comment by bblue** [comment]
Fixed it. Seems the crawler is blocked by the server when no user agent is defined.

**Comment by bblue** [comment]
hmm... the user agent fixed the connection from my development computer, but I still get a 404 when connecting from github-servers.

**Comment by presidento23** [comment]
Where did you change the user agent? Was it in pipwin.py in the headers variable?

**Comment by bblue** [comment]
> Where did you change the user agent? Was it in pipwin.py in the headers variable?

Just see my pull request. All there.
https://github.com/lepisma/pipwin/pull/44/files

**Comment by samapriya** [comment]
Hi @lepisma 
This issue was because of the way beautifulsoup4 handles string vs text. Fixed this in the pull request for release 0.5.0. @bblue we have removed robobrowser since version 0.4.7. @presidento23 you can try it out using while we wait for merge. :) 

```
pip install git+https://github.com/samapriya/pipwin.git
```

**Comment by samapriya** [comment]
Hey @lepisma 
Would you mind merging and releasing to v0.5.0. Thank you :)

**Comment by This-is-NB** [comment]
I am not able to use pipwin 
i checked "pip show pipwin"
its updated and there

but when i use any pipwin command it shows

'pipwin' is not recognized as an internal or external command,
operable program or batch file.

any help would be grateful!
@samapriya 
Thanks

**Comment by samapriya** [comment]
Hi @This-is-NB 

* Try the ```pip show pipwin``` again
* Copy the Location path
* Add this to the Path variable in System Variables under your system properties.

Try google adding to system variables windows that should help. Close the cmd and restart again and it should hopefully work

**Comment by This-is-NB** [comment]
Helli @samapriya 
I did as you said 
And added the path shown in 
`pip show pipwin`

To system variables as well as user one just to be safe 
And restarted cmd
But no fruit from this either 
Its showing the same error 
Pipwin is not recognized as an internal or external command
Still it

**Comment by This-is-NB** [comment]
@samapriya 
I'm using python 3.8
and i found on stack that it doesn't work with 3.7 and above 
is it true??
if it is true any alternatives??
